# Generated by Django 5.2.7 on 2025-10-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('num_personas', models.IntegerField()),
            ],
        ),
    ]
